-- ============================================================
-- Week 3 Assignment — Section 2 & 3 Schema (READY-MADE)
-- Paste this ENTIRE file into MySQL Workbench / phpMyAdmin and
-- run it once. This creates the schema + data you will write
-- your Section 2 (Medium) and Section 3 (Hard) queries against.
--
-- Do NOT edit this file. Write your queries in a NEW file called
-- section2_3_queries.sql
-- ============================================================

DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
    id INT PRIMARY KEY,
    department_name VARCHAR(50),
    location VARCHAR(50)
);

CREATE TABLE employees (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    department VARCHAR(30),
    dept_id INT,
    salary DECIMAL(10,2),
    bonus DECIMAL(10,2),
    manager_id INT,
    hire_date DATE,
    FOREIGN KEY (dept_id) REFERENCES departments(id)
);

INSERT INTO departments (id, department_name, location) VALUES
(1, 'IT', 'Lahore'),
(2, 'Sales', 'Karachi'),
(3, 'HR', 'Islamabad'),
(4, 'Finance', 'Lahore'),
(5, 'Marketing', 'Karachi');

INSERT INTO employees (id, name, department, dept_id, salary, bonus, manager_id, hire_date) VALUES
(1,  'Ali',     'IT',        1, 95000, 5000, NULL, '2019-03-11'),
(2,  'Sara',    'IT',        1, 72000, 3000, 1,    '2020-06-15'),
(3,  'Usman',   'IT',        1, 68000, NULL, 1,    '2021-01-20'),
(4,  'Fatima',  'IT',        1, 61000, 2000, 1,    '2022-08-05'),
(5,  'Hamza',   'Sales',     2, 58000, 4000, NULL, '2018-11-01'),
(6,  'Ayesha',  'Sales',     2, 62000, NULL, 5,    '2019-09-14'),
(7,  'Bilal',   'Sales',     2, 54000, 1500, 5,    '2021-04-22'),
(8,  'Mariam',  'Sales',     2, 59000, 2500, 5,    '2022-02-10'),
(9,  'Zainab',  'HR',        3, 50000, NULL, NULL, '2017-07-19'),
(10, 'Hassan',  'HR',        3, 48000, 1000, 9,    '2020-12-01'),
(11, 'Sana',    'HR',        3, 52000, NULL, 9,    '2023-01-15'),
(12, 'Kamran',  'Finance',   4, 88000, 6000, NULL, '2016-05-30'),
(13, 'Nida',    'Finance',   4, 71000, 3000, 12,   '2019-10-08'),
(14, 'Omar',    'Finance',   4, 67000, NULL, 12,   '2021-06-17'),
(15, 'Iqra',    'Finance',   4, 73000, 2500, 12,   '2020-03-25'),
(16, 'Tariq',   'Marketing', 5, 56000, 1800, NULL, '2018-02-14'),
(17, 'Rabia',   'Marketing', 5, 60000, NULL, 16,   '2022-09-09'),
(18, 'Asad',    'Marketing', 5, 55000, 1200, 16,   '2023-05-03'),
(19, 'Mahnoor', 'IT',        1, 64000, 2200, 1,    '2023-07-12'),
(20, 'Danish',  'Sales',     2, 57000, NULL, 5,    '2021-11-28');

-- Quick check — run these to confirm the schema loaded correctly
SELECT * FROM departments;
SELECT * FROM employees;

-- medium queries section B 

-- 1. What's the average salary in each department?
SELECT department, AVG(salary) AS avg_salary 
FROM employees 
GROUP BY department;

-- 2. Which departments pay above-average? (avg > 60k)
SELECT department, AVG(salary) AS avg_salary 
FROM employees 
GROUP BY department 
HAVING AVG(salary) > 60000;

-- 3. How many people work in each department?
SELECT department, COUNT(name) AS total_employee 
FROM employees 
GROUP BY department;

-- 4. Show me every employee with their department name and location
SELECT employees.name, departments.department_name, departments.location 
FROM employees 
INNER JOIN departments 
ON employees.dept_id = departments.id;

-- 5. List all employees — even if their department isn't in the departments table
SELECT e.name, d.department_name
FROM employees e
LEFT JOIN departments d
ON e.dept_id = d.id;

-- 6. Who earns more than the company average?
SELECT name, salary 
FROM employees 
WHERE salary > (SELECT AVG(salary) FROM employees);

-- 7. Which departments actually have people working in them?
SELECT d.department_name
FROM departments d
WHERE EXISTS (
    SELECT 1 
    FROM employees e 
    WHERE e.dept_id = d.id
);

-- 8. Who reports to whom? Show employee + their manager
SELECT e.name AS employee, m.name AS manager
FROM employees e
LEFT JOIN employees m ON e.manager_id = m.id;

-- 9. What's everyone's total pay? Treat missing bonus as zero
SELECT 
    name, 
    salary, 
    COALESCE(bonus, 0) AS bonus,
    salary + COALESCE(bonus, 0) AS total_pay
FROM employees;

-- 10. Who joined the company in 2021?
SELECT * FROM employees 
WHERE YEAR(hire_date) = 2021;




--  Section 3 (Hard) Queries


-- 1. Rank everyone by salary within their own department
SELECT name, department, salary,
       RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS salary_rank
FROM employees;

-- 2. Top 2 earners in every department
SELECT * FROM (
    SELECT name, department, salary,
           ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn
    FROM employees
) ranked
WHERE rn <= 2;

-- 3. Show each person's salary and the next-lower salary in their dept
SELECT name, department, salary,
       LEAD(salary) OVER (PARTITION BY department ORDER BY salary DESC) AS next_lower_salary
FROM employees;

-- 4. CTE: Count high earners (>60k) per department
WITH high_earners AS (
    SELECT name, department, salary
    FROM employees
    WHERE salary > 60000
)
SELECT department, COUNT(*) AS high_count FROM high_earners GROUP BY department ORDER BY high_count DESC;

-- 5. Merge IT and Sales names into one list, no duplicates
SELECT name FROM employees WHERE department = 'IT'UNION SELECT name FROM employees WHERE department = 'Sales';

-- 6. Department stats, but only where average pay is above 55k
SELECT d.department_name, d.location, 
       AVG(e.salary) AS avg_salary, 
       COUNT(e.name) AS employee_count
FROM departments d 
JOIN employees e ON d.id = e.dept_id 
GROUP BY d.id, d.department_name, d.location 
HAVING avg_salary > 55000;

-- 7. Who earns more than their own department's average?
SELECT name, department, salary
FROM employees e
WHERE salary > (
    SELECT AVG(salary) 
    FROM employees 
    WHERE department = e.department
);

-- 8. Find all managers (people who manage at least one other employee)
SELECT name, id
FROM employees
WHERE id IN (
    SELECT DISTINCT manager_id 
    FROM employees 
    WHERE manager_id IS NOT NULL
);